language: elixir
env:
   - ELIXIR_ERL_OPTIONS="+T 9"
elixir:
    - 1.2.6
    - 1.3.0
    - 1.3.4
otp_release:
    - 18.3
    - 19.1
matrix:
    include:
        - elixir: 1.2.0
          otp_release: 18.2
sudo: false
script:
      - mix test.all
